#!/usr/bin/env python
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

from datetime import datetime
import re

def main():
	with open("index.html", "r") as f:
		contents = f.read()

	match = re.findall("Last updated \w+ \d+", contents)
	if not match:
		raise Exception("No match found")
	for m in match:
		if m != f"Last updated {datetime.now().strftime('%B %Y')}":
			raise Exception(f"Match has not been updated to correct month and year: '{m}'")

if __name__=="__main__":
	main()

